### ISSUE TITLE
{   "error": "Undefined offset: 515" }

### ISSUE THREAD

**Issue by danireginatto** [markhuot/craftql#214] opened 2019-01-23 13:01 UTC
My CraftQL died on version 3.1.3.
CraftQL version 1.2.1

Have you a prevision about new release for correction on this problem?

**Comment by markhuot** [comment] 2019-01-23 14:43
Duplicate of #210. I'll get a stable release cut shortly to resolve this.

**Closed by markhuot** 2019-01-23 14:43 UTC
