### ISSUE TITLE
Plans to take craft user permissions into account?

### ISSUE THREAD

**Issue by menberg** [markhuot/craftql#61] opened 2018-02-12 12:58 UTC
Hi Mark

Seeing this comment I was wondering if this is something we'll see soon
https://github.com/markhuot/craftql/blob/950a6410e25fba8ffb3a14e21343050a6a29c8c0/src/Controllers/ApiController.php#L56

What are your plans about this?

Thanks!

**Comment by markhuot** [comment] 2018-02-12 16:31
This line should probably be removed. CraftQL uses its own scopes to manage permissions outside Craft's native permission system.

I'd like to explore using Craft's permission functionality at some point, but I don't know that native permissions map perfectly to GraphQL.

**Comment by menberg** [comment] 2018-02-12 21:47
How can we give a user the rights to modify only his entries, but not the entries of other users? Is this already possible with CraftQL?

**Comment by markhuot** [comment] 2018-02-13 14:52
This isn't currently possible in CraftQL. I'll explore adding it in but I don't have an estimate on timing.

**Comment by markhuot** [comment] 2018-05-30 21:17
Closing as a duplicate of #85

**Closed by markhuot** 2018-05-30 21:17 UTC
Labels: feature request
