### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by Tam** [markhuot/craftql#32] opened 2017-11-30 11:25 UTC
Fresh install, Craft Pro 3.0.0-RC1 & CraftQL 1.0.0-beta.23. Error thrown on `/admin/craftql/browse`.

It looks like the JS is trying to find the `#page-header` element, which doesn't exist.

```js
var header = document.querySelector('#page-header');
header.parentNode.removeChild(header);
```

**Comment by markhuot** [comment] 2017-11-30 13:42
Duplicate of #27.

An update to `dev-master` should fix this.

**Closed** 2017-11-30 13:43 UTC
