### ISSUE TITLE
Doesn't fetch categories data in Matrix field with craftql after update latest version

### ISSUE THREAD

**Issue by superstar1025** [markhuot/craftql#212] opened 2019-01-22 03:57 UTC
I have added categories in Matrix field so when I use craftcms version 3.0, craftql is working as well.
but I updated craftcms with latest version 3.1.3 today by the way I can't fetch categories data in Matrix field using craftql.
This is submenu Matrix field:
![screen shot 2019-01-21 at 9 51 41 pm](https://user-images.githubusercontent.com/44493957/51511498-22bcb280-1dc7-11e9-9f39-71deee1a929c.png)
and then I added categories in globals.
This is Globals screen.
![screen shot 2019-01-21 at 9 52 07 pm](https://user-images.githubusercontent.com/44493957/51511528-4253db00-1dc7-11e9-924c-92c272e033ae.png)
currently added "Sub Product categories" and "Top Brands" categories to Matrix field.
but doesn't exist categories in graphql schema.
This is craftql query result:
![screen shot 2019-01-21 at 9 53 27 pm](https://user-images.githubusercontent.com/44493957/51511597-7f1fd200-1dc7-11e9-8303-5048409740da.png)

**Comment by gusnips** [comment] 2019-01-22 23:33
+1

**Comment by danireginatto** [comment] 2019-01-22 23:38
+1

**Comment by superstar1025** [comment] 2019-01-23 01:03
Before CraftCMS update, It fetched category data with craftql query.
![screen shot 2019-01-23 at 2 02 51 am](https://user-images.githubusercontent.com/44493957/51575606-08600300-1eb3-11e9-8bda-3d693f798224.png)
This is screen when it is working as well.

**Comment by LeeCampbellr** [comment] 2019-01-23 02:38
+1

**Comment by markhuot** [comment] 2019-01-23 14:44
This is a duplicate of #210. I'll get a stable release cut shortly to address this.

**Closed by markhuot** 2019-01-23 14:44 UTC
