### ISSUE TITLE
Can not query the Category field in entry

### ISSUE THREAD

**Issue by dsteinel** [markhuot/craftql#213] opened 2019-01-22 09:10 UTC
It seems like I can not access a category field from CraftQL when I assign it to an entry. 

What I did:
* I added to an **Entry Type** a field of type **Category** (handle: "articleCategory")
* I added some categories
* From an entry I chose a category
* The handle "articleCategory" does not show in the documentation explorer

Except for this, all queries work. Also when I assign another type to my "articleCategory" field, the documentation explorer shows the field.

Issue: The field type **Category** should show in the Query if I assign it to an entry type.

**Comment by dsteinel** [comment] 2019-01-22 12:05
Seems to be duplicate of #212

**Comment by gusnips** [comment] 2019-01-22 23:32
+1

**Comment by danireginatto** [comment] 2019-01-22 23:39
+1

**Comment by markhuot** [comment] 2019-01-23 14:48
Is this on Craft 3.1.x?

If so then it is indeed a duplicate of #212 and, more specifically, #210, which I'm using to track the fix. I have an update on `dev-master` that I'm testing and will get a release cut for. I'm going to close this ticket for now. However, if anyone is having this issue on 3.0.x please re-open and let me know.

**Closed by markhuot** 2019-01-23 14:48 UTC

**Comment by dsteinel** [comment] 2019-01-23 14:50
Thanks @markhuot && yes, it is on Craft 3.1.x

**Comment by danireginatto** [comment] 2019-01-23 16:14
Can we help in any way?


Daniel Reginatto
daniel@reginatto.com

**Comment by markhuot** [comment] 2019-01-23 16:15
If you're able to update your `composer.json` to point to `dev-master` and confirm categories are now working that would be helpful.

**Comment by danireginatto** [comment] 2019-01-23 16:50
I found an error in the author field only, relative to the photo field.





Daniel Reginatto
daniel@reginatto.com
